# Generated by Django 6.0.5 on 2026-09-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service_name', models.CharField(max_length=200)),
                ('doctor_name', models.CharField(default='Dr. Anoop', max_length=150)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(default='Senior Dental Surgeon', max_length=150)),
                ('qualification', models.CharField(help_text='e.g. BDS, MDS (Implantology)', max_length=200)),
                ('specialization', models.CharField(max_length=150)),
                ('experience_years', models.IntegerField(default=15)),
                ('bio', models.TextField()),
                ('avatar_url', models.CharField(blank=True, help_text='Image URL or SVG icon', max_length=300)),
                ('is_chief', models.BooleanField(default=False)),
                ('available_days', models.CharField(default='Mon - Sat', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('general', 'General & Preventive'), ('cosmetic', 'Cosmetic & Whitening'), ('implant', 'Implants & Surgery'), ('ortho', 'Braces & Aligners'), ('rootcanal', 'Root Canal Therapy'), ('pediatric', 'Pediatric Dentistry')], default='general', max_length=50)),
                ('icon_name', models.CharField(default='tooth', help_text='FontAwesome icon class name', max_length=50)),
                ('short_description', models.CharField(max_length=300)),
                ('detailed_description', models.TextField()),
                ('duration', models.CharField(default='30-45 Mins', max_length=100)),
                ('price_estimate', models.CharField(default='Affordable Care', max_length=100)),
                ('badge_tag', models.CharField(blank=True, default='Popular', max_length=50)),
                ('is_featured', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('rating', models.IntegerField(default=5)),
                ('review_text', models.TextField()),
                ('treatment', models.CharField(default='General Dentistry', max_length=150)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
