# Generated by Django 6.0.5 on 2026-09-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone2',
            field=models.CharField(blank=True, help_text='Alternate Phone Number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, help_text='Comments / Notes', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='preferred_time',
            field=models.CharField(blank=True, default='Morning (09:30 AM - 12:00 PM)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service_name',
            field=models.CharField(blank=True, default='General Consultation', max_length=200, null=True),
        ),
    ]
