# Generated by Django 6.0.5 on 2026-09-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dental', '0003_appointment_age_appointment_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=50, unique=True)),
                ('patient_name', models.CharField(max_length=150)),
                ('doctor_name', models.CharField(default='Dr. Anoop', max_length=150)),
                ('case_type', models.CharField(default='Crown & Bridge', max_length=100)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('pending', 'Pending Review')], default='in_progress', max_length=30)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=50, unique=True)),
                ('patient_name', models.CharField(max_length=150)),
                ('treatment', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Partial', 'Partial')], default='Paid', max_length=50)),
                ('payment_mode', models.CharField(default='UPI / Card', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
