# Generated by Django 6.0.5 on 2026-09-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dental', '0004_dentalcase_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, help_text='Doctor profile photo', null=True, upload_to='doctors/'),
        ),
    ]
