# Generated by Django 6.0.5 on 2026-09-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dental', '0005_doctor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='designation',
            field=models.CharField(blank=True, default='', help_text='e.g. Senior Dental Surgeon', max_length=150),
        ),
        migrations.AddField(
            model_name='doctor',
            name='reg_no',
            field=models.CharField(blank=True, default='', help_text='Registration Number', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(blank=True, default='Senior Dental Surgeon', max_length=150),
        ),
    ]
