# Generated by Django 6.0.5 on 2026-09-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dental', '0006_doctor_designation_doctor_reg_no_alter_doctor_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='chart_data',
            field=models.TextField(blank=True, default='{}', help_text='JSON teeth chart data', null=True),
        ),
    ]
