# Generated by Django 6.0.5 on 2026-09-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dental', '0007_appointment_chart_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Service photo or banner image', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='detailed_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
