# Generated by Django 6.0.5 on 2026-09-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dental', '0008_service_image_alter_service_detailed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, help_text='Patient photo or smile image', null=True, upload_to='testimonials/'),
        ),
    ]
