# Generated by Django 6.0.5 on 2026-10-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dental', '0009_testimonial_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='About Our Clinic', max_length=150)),
                ('title', models.CharField(default='Your Trusted Partner For Total Oral Health', max_length=200)),
                ('description', models.TextField(default='Anupam Dental Clinic, led by Dr. Anoop, has been caring for patients since 19th August 1996. For nearly three decades, we have remained committed to ethical dentistry, clear communication, and compassionate care.')),
                ('photo', models.ImageField(blank=True, help_text='Clinic about section photo', null=True, upload_to='about/')),
                ('experience_years', models.CharField(blank=True, default='28+', max_length=50)),
                ('established_date', models.CharField(blank=True, default='19th August 1996', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
