# Generated by Django 6.0.5 on 2026-10-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dental', '0010_aboutclinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutclinic',
            name='facility_location',
            field=models.CharField(blank=True, default='Anupam Dental Clinic, Vaikom / Cherthala, Kerala, India', max_length=250),
        ),
        migrations.AddField(
            model_name='aboutclinic',
            name='helpline',
            field=models.CharField(blank=True, default='Call / WhatsApp: +91 94460 46868 | Email: info@anupamdental.com', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutclinic',
            name='operating_hours',
            field=models.CharField(blank=True, default='Mon - Sun: 9:00 AM – 8:00 PM (Tuesday Holiday)', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutclinic',
            name='sterilization_safety',
            field=models.CharField(blank=True, default='Class-B 7-Step Autoclaving, UV sterilization chambers, 100% infection control.', max_length=300),
        ),
        migrations.AlterField(
            model_name='aboutclinic',
            name='description',
            field=models.TextField(default='Our Philosophy\nWe believe that trust is the foundation of good dental care. Every treatment at our clinic begins only after a detailed explanation of the diagnosis and treatment plan, helping patients and their families make informed and confident decisions.\n\nEthics & Safety First\nFrom day one, we have strictly followed ethical dental practices with zero compromise on sterilization and infection control protocols. Your safety and well-being are always our highest priorities.\n\nTrusted by Generations\nOur journey has been shaped by the trust of our patients. The clinic continues to grow through word-of-mouth recommendations, reflecting the confidence and satisfaction of the families we serve.\n\nComprehensive Dental Care\nWith specialists across all dental specialties, we provide complete and personalized dental solutions for patients of all ages—under one roof.\n\nGentle Care for Children\nWe offer special care and attention to pediatric patients, creating a friendly and comforting environment that helps children feel relaxed and happy during their visits.'),
        ),
    ]
