# Generated by Django 6.0.5 on 2026-10-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dental', '0011_aboutclinic_facility_location_aboutclinic_helpline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Clinic Gallery Photo', max_length=150)),
                ('caption', models.CharField(blank=True, default='', max_length=250)),
                ('image', models.ImageField(help_text='Clinic or Smile photo', upload_to='gallery/')),
                ('category', models.CharField(choices=[('clinic', 'Clinic Interior & Operatory'), ('equipment', 'Advanced Dental Technology'), ('smile', 'Smile Transformations'), ('sterilization', 'Sterilization & Patient Safety')], default='clinic', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
